version: '3.8'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - wincrics_networkk

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./privatekey.pem:/etc/nginx/certs/privatekey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - react
    networks:
      - wincrics_networkk

networks:
  wincrics_networkk:
    driver: bridge
