import React from 'react';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import Slide from '@mui/material/Slide';

const Policy = () => {
  const sections = [
    { title: 'Last updated:', content: '26/05/2024' },
    { title: 'Privacy notice for Wincrics.com', content: 'This privacy notice for Wincrics.com ("we," "us," or "our") describes how and why we might collect, store, use, and/or share ("process") your information when you use our services ("Services"), such as when you: [List examples of when the services are used]' },
    { title: 'Questions or concerns?', content: 'Reading this privacy notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services.' },
    { title: 'SUMMARY OF KEY POINTS', content: 'This summary provides key points from our privacy notice. You can find more details about any of these topics by clicking the link following each key point or by using our table of contents below to find the section you are looking for. - What personal information do we process? - Do we process any sensitive personal information? - Do we collect any information from third parties? - How do we process your information? - In what situations and with which parties do we share personal information? - What are your rights? - How do you exercise your rights?' },
    { title: 'TABLE OF CONTENTS', content: '1. WHAT INFORMATION DO WE COLLECT? 2. HOW DO WE PROCESS YOUR INFORMATION? 3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION? 4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES? 5. HOW DO WE HANDLE YOUR SOCIAL LOGINS? 6. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY? 7. HOW LONG DO WE KEEP YOUR INFORMATION? 8. DO WE COLLECT INFORMATION FROM MINORS? 9. WHAT ARE YOUR PRIVACY RIGHTS? 10. CONTROLS FOR DO-NOT-TRACK FEATURES 11. DO WE MAKE UPDATES TO THIS NOTICE? 12. HOW CAN YOU CONTACT US ABOUT THIS NOTICE? 13. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?' },
    { title: 'WHAT INFORMATION DO WE COLLECT?', content: 'Personal information you disclose to us - In Short: We collect personal information that you provide to us. We collect personal information that you voluntarily provide to us when you register on the Services, express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us. - Sensitive Information: We do not process sensitive information. - All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information. Information automatically collected - In Short: Some information – such as your Internet Protocol (IP) address and/or browser and device characteristics – is collected automatically when you visit our Services. We automatically collect certain information when you visit, use, or navigate the Services. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Services, and other technical information. This information is primarily needed to maintain the security and operation of our Services and for our internal analytics and reporting purposes. Like many businesses, we also collect information through cookies and similar technologies.' },
    { title: 'HOW DO WE PROCESS YOUR INFORMATION?', content: `In Short: We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent.
    We process your personal information for a variety of reasons, depending on how you interact with our Services,` },
    { title: 'WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?', content: `In Short: We may share information in specific situations described in this section and/or with the following third parties.
    We may need to share your personal information in the following situations:
    * Business Transfers: We may share or transfer your information in connection with or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.
    * Affiliates: We may share your information with our affiliates, in which case we will require those affiliates to honor this privacy notice. Affiliates include our parent company and any subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.` },
    { title: 'DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?', content: `In Short: We may use cookies and other tracking technologies to collect and store your information.
    We may use cookies and similar tracking technologies (like web beacons and pixels) to gather information when you interact with our Services. Some online tracking technologies help us maintain the security of our Services, prevent crashes, fix bugs, save your preferences, and assist with basic site functions.
    We also permit third parties and service providers to use online tracking technologies on our Services for analytics and advertising, including to help manage and display advertisements, to tailor advertisements to your interests, or to send abandoned shopping cart reminders (depending on your communication preferences). The third parties and service providers use their technology to provide advertising about products and services tailored to your interests which may appear either on our Services or on other websites.` },
    { title: 'HOW DO WE HANDLE YOUR SOCIAL LOGINS?', content: `In Short: If you choose to register or log in to our Services using a social media account, we may have access to certain information about you.
    Our Services offer you the ability to register and log in using your third-party social media account details (like your Facebook or X logins). Where you choose to do this, we will receive certain profile information about you from your social media provider. The profile information we receive may vary depending on the social media provider concerned but will often include your name, email address, friends list, and profile picture, as well as other information you choose to make public on such a social media platform.
    We will use the information we receive only for the purposes that are described in this privacy notice or that are otherwise made clear to you on the relevant Services. Please note that we do not control, and are not responsible for, other uses of your personal information by your third-party social media provider. We recommend that you review their privacy notice to understand how they collect, use, and share your personal information, and how you can set your privacy preferences on their sites and apps.` },
    { title: 'IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?', content: `In Short: We may transfer, store, and process your information in countries other than your own.
    Our servers are located in [insert locations]. If you are accessing our Services from outside [insert country/region], please be aware that your information may be transferred to, stored, and processed by us in our facilities and by those third parties with whom we may share your personal information (see "WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?" above), in and other countries.
    If you are a resident in the European Economic Area (EEA), United Kingdom (UK), or Switzerland, then these countries may not necessarily have data protection laws or other similar laws as comprehensive as those in your country. However, we will take all necessary measures to protect your personal information in accordance with this privacy notice and applicable law.` },
    { title: 'HOW LONG DO WE KEEP YOUR INFORMATION?', content: `In Short: We keep your information for as long as necessary to fulfil the purposes outlined in this privacy notice unless otherwise required by law.
    We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements).
    When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.` },
    { title: 'DO WE COLLECT INFORMATION FROM MINORS?', content: `In Short: We do not knowingly collect data from or market to children under 18 years of age.
    We do not knowingly collect, solicit data from, or market to children under 18 years of age, nor do we knowingly sell such personal information. By using the Services, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent's use of the Services. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we may have collected from children under age 18, please contact us` },
    { title: 'WHAT ARE YOUR PRIVACY RIGHTS?', content: `In Short: You may review, change, or terminate your account at any time, depending on your country, province, or state of residence.
    * Withdrawing your consent: If we are relying on your consent to process your personal information, which may be express and/or implied consent depending on the applicable law, you have the right to withdraw your consent at any time. You can withdraw your consent at any time by contacting us using the contact details provided in the section "HOW CAN YOU CONTACT US ABOUT THIS NOTICE?" below.
    * However, please note that this will not affect the lawfulness of the processing before its withdrawal nor, when applicable law allows, will it affect the processing of your personal information conducted in reliance on lawful processing grounds other than consent.
    * Account Information: If you would at any time like to review or change the information in your account or terminate your account, you can:
        * [Provide instructions on how to review, change, or terminate the account]
    Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, we may retain some information in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our legal terms, and/or comply with applicable legal requirements.` },
    { title: 'CONTROLS FOR DO-NOT-TRACK FEATURES', content: `Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track ("DNT") feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. At this stage, no uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice.` },
    { title: 'DO WE MAKE UPDATES TO THIS NOTICE?', content: `In Short: Yes, we will update this notice as necessary to stay compliant with relevant laws.
    We may update this privacy notice from time to time. The updated version will be indicated by an updated "Revised" date at the top of this privacy notice. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice frequently to be informed of how we are protecting your information.` },
    { title: 'HOW CAN YOU CONTACT US ABOUT THIS NOTICE?', content: `HOW CAN YOU CONTACT US ABOUT THIS NOTICE?
    If you have questions or comments about this notice, you may contact us by post at:
    * [wincricsinfotech@gmail.com]` },
    { title: 'HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?', content: `Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, details about how we have processed it, correct inaccuracies, or delete your personal information. You may also have the right to withdraw your consent to our processing of your personal information. These rights may be limited in some circumstances by applicable law. To request to review, update, or delete your personal information, please fill out and submit a data subject access request:
    * [by contact us page]` },
    
  ];

  return (
    <Box sx={{ width: '100%', marginTop: '20px' }}>
      {sections.map((section, index) => (
        <Slide direction="left" in={true} mountOnEnter unmountOnExit key={index}>
          <Box>
            <Typography variant="h5" paragraph>{section.title}</Typography>
            <Typography variant="body1" paragraph>{section.content}</Typography>
          </Box>
        </Slide>
      ))}
    </Box>
  );
}

export default Policy;
