version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: wincrics_db
      POSTGRES_USER: wincrics_hiijethalal
      POSTGRES_PASSWORD: wincrics_hiijethalal@1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wincrics_network

  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - wincrics_network

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./privatekey.pem:/etc/nginx/certs/privatekey.pem
    ports:
      - "8443:8443"
    depends_on:
      - node
    networks:
      - wincrics_network


networks:
  wincrics_network:

volumes:
  pgdata:
